# Generated by Django 5.0.7 on 2025-02-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetdelightsapp1', '0010_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='selected_price_option',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
