# Generated by Django 5.1.2 on 2025-02-12 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetdelightsapp1', '0017_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('order_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('selected_price_option', models.CharField(max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweetdelightsapp1.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweetdelightsapp1.product')),
            ],
        ),
    ]
