# Generated by Django 5.1.2 on 2025-02-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetdelightsapp1', '0018_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_different_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
