# Generated by Django 5.1.2 on 2025-02-13 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetdelightsapp1', '0019_order_is_different_address_order_shipping_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCancel',
            fields=[
                ('cancel_id', models.AutoField(primary_key=True, serialize=False)),
                ('cancel_reason', models.TextField()),
                ('cancel_datetime', models.DateTimeField(auto_now_add=True)),
                ('refund_status', models.CharField(choices=[('Pending', 'Pending'), ('Processed', 'Processed'), ('Not Applicable', 'Not Applicable')], default='Pending', max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweetdelightsapp1.order')),
            ],
        ),
    ]
