# Generated by Django 5.1.2 on 2025-02-14 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweetdelightsapp1', '0025_shop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderCancelDetails',
        ),
    ]
