# Generated by Django 5.1.2 on 2025-02-14 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetdelightsapp1', '0026_delete_ordercanceldetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCancelDetails',
            fields=[
                ('cancel_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_canceled', models.PositiveIntegerField(default=1)),
                ('cancel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweetdelightsapp1.ordercancel')),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweetdelightsapp1.orderdetails')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweetdelightsapp1.product')),
            ],
        ),
    ]
