# Generated by Django 5.1.2 on 2025-02-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetdelightsapp1', '0027_ordercanceldetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercancel',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
