# Generated by Django 5.1.2 on 2025-02-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetdelightsapp1', '0030_remove_orderreturn_refund_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercancel',
            name='refund_amount',
        ),
        migrations.RemoveField(
            model_name='ordercancel',
            name='refund_status',
        ),
        migrations.AddField(
            model_name='ordercanceldetails',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ordercanceldetails',
            name='refund_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processed', 'Processed'), ('Not Applicable', 'Not Applicable')], default='Pending', max_length=20),
        ),
    ]
