# Generated by Django 5.1.2 on 2025-02-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetdelightsapp1', '0031_remove_ordercancel_refund_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderreturn',
            name='return_reason',
        ),
        migrations.RemoveField(
            model_name='orderreturn',
            name='return_status',
        ),
        migrations.AddField(
            model_name='orderreturndetails',
            name='return_reason',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderreturndetails',
            name='return_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
