# Generated by Django 5.1.2 on 2025-02-28 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetdelightsapp1', '0033_customorder_order_custom_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sweetdelightsapp1.productpayment'),
        ),
    ]
