# Generated by Django 5.1.2 on 2025-03-01 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweetdelightsapp1', '0034_customorder_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='custom_order',
        ),
        migrations.DeleteModel(
            name='CustomOrder',
        ),
    ]
