# Generated by Django 5.1.2 on 2025-03-01 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetdelightsapp1', '0035_remove_order_custom_order_delete_customorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpayment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sweetdelightsapp1.user'),
            preserve_default=False,
        ),
    ]
