# Generated by Django 5.1.2 on 2025-03-01 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetdelightsapp1', '0039_remove_productpayment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpayment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sweetdelightsapp1.user'),
        ),
    ]
