# Generated by Django 5.1.2 on 2025-03-03 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweetdelightsapp1', '0048_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
