# Generated by Django 5.1.2 on 2025-03-22 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetdelightsapp1', '0049_delete_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='CakeLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CakeSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dietary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Filling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('sugar_option', models.CharField(max_length=50)),
                ('delivery_date', models.DateField()),
                ('delivery_address', models.TextField()),
                ('delivery_time', models.CharField(max_length=50)),
                ('hidden_filling', models.CharField(max_length=50)),
                ('cake_topper', models.CharField(max_length=50)),
                ('gift_message', models.TextField()),
                ('additional_notes', models.TextField()),
                ('cake_image', models.ImageField(upload_to='cake_images/')),
                ('cake_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweetdelightsapp1.cakesize')),
                ('cakelayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweetdelightsapp1.cakelayer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweetdelightsapp1.user')),
                ('dietary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweetdelightsapp1.dietary')),
                ('filling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweetdelightsapp1.filling')),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweetdelightsapp1.flavor')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweetdelightsapp1.topping')),
            ],
        ),
    ]
