# Generated by Django 5.1.2 on 2025-03-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetdelightsapp1', '0051_customorder_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customorder',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
        migrations.AddField(
            model_name='customorder',
            name='payment_due',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready_for_payment', 'Ready for Payment'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='customorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10),
        ),
    ]
