# Generated by Django 5.1.2 on 2025-03-22 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweetdelightsapp1', '0053_alter_customorder_paid_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customorder',
            name='cakelayer',
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='cake_size',
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='dietary',
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='filling',
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='flavor',
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='topping',
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='user',
        ),
        migrations.DeleteModel(
            name='CakeLayer',
        ),
        migrations.DeleteModel(
            name='CakeSize',
        ),
        migrations.DeleteModel(
            name='Dietary',
        ),
        migrations.DeleteModel(
            name='Filling',
        ),
        migrations.DeleteModel(
            name='Flavor',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
        migrations.DeleteModel(
            name='CustomOrder',
        ),
    ]
