# Generated by Django 5.1.2 on 2025-03-25 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetdelightsapp1', '0058_orderdetails_cake_customization'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCakeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake_type', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('shape', models.CharField(max_length=50)),
                ('flavor', models.CharField(max_length=50)),
                ('filling', models.CharField(max_length=50)),
                ('icing', models.CharField(max_length=50)),
                ('cake_layers', models.CharField(max_length=50)),
                ('occasion', models.CharField(blank=True, max_length=50, null=True)),
                ('cake_texture', models.CharField(blank=True, max_length=50, null=True)),
                ('sweetness_level', models.CharField(max_length=50)),
                ('serving_size', models.CharField(max_length=50)),
                ('cake_theme', models.TextField(blank=True, null=True)),
                ('allergy_info', models.TextField(blank=True, null=True)),
                ('egg_preference', models.CharField(choices=[('with_egg', 'With Egg'), ('without_egg', 'Without Egg')], max_length=20)),
                ('dietary_preferences', models.TextField(blank=True, null=True)),
                ('extra_addons', models.TextField(blank=True, null=True)),
                ('packaging', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('additional_customization', models.TextField(blank=True, null=True)),
                ('hidden_surprise', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cake_orders/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('processing', 'Processing'), ('ready', 'Ready for Pickup'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='ordered', max_length=20)),
                ('admin_response', models.TextField(blank=True, null=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_cake', to='sweetdelightsapp1.order')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sweetdelightsapp1.productpayment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweetdelightsapp1.user')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='custom_cake_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_info', to='sweetdelightsapp1.customcakeorder'),
        ),
    ]
