# Generated by Django 5.1.2 on 2025-03-25 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetdelightsapp1', '0059_customcakeorder_order_custom_cake_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='custom_cake_order',
        ),
        migrations.AlterField(
            model_name='customcakeorder',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_cake_order', to='sweetdelightsapp1.order'),
        ),
    ]
