# Generated by Django 5.1.2 on 2025-03-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetdelightsapp1', '0060_remove_order_custom_cake_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcakeorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
