# Generated by Django 5.1.2 on 2025-03-25 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetdelightsapp1', '0061_customcakeorder_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='custom_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sweetdelightsapp1.customcakeorder'),
        ),
    ]
