# Generated by Django 5.1.2 on 2025-03-25 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweetdelightsapp1', '0062_cart_custom_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='custom_order',
        ),
    ]
