# Generated by Django 5.1.2 on 2025-03-26 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetdelightsapp1', '0063_remove_cart_custom_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcakeorder',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sweetdelightsapp1.discount'),
        ),
    ]
