# Generated by Django 5.1.2 on 2025-03-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetdelightsapp1', '0065_alter_customcakeorder_pickup_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcakeorder',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=1500, max_digits=10),
        ),
        migrations.AddField(
            model_name='customcakeorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customcakeorder',
            name='discount_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
