# Generated by Django 5.1.2 on 2025-03-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetdelightsapp1', '0066_customcakeorder_base_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customcakeorder',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='customcakeorder',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='customcakeorder',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='customcakeorder',
            name='discount_code',
        ),
        migrations.AlterField(
            model_name='customcakeorder',
            name='pickup_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customcakeorder',
            name='pickup_time',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
    ]
