# Generated by Django 5.1.2 on 2025-03-26 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetdelightsapp1', '0067_remove_customcakeorder_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcakeorder',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=1500, max_digits=10),
        ),
        migrations.AddField(
            model_name='customcakeorder',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sweetdelightsapp1.discount'),
        ),
        migrations.AddField(
            model_name='customcakeorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customcakeorder',
            name='discount_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customcakeorder',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customcakeorder',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
