# Generated by Django 5.1.2 on 2025-03-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetdelightsapp1', '0069_remove_customcakeorder_base_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcakeorder',
            name='pickup_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customcakeorder',
            name='pickup_time',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
    ]
