# Generated by Django 5.1.2 on 2025-03-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetdelightsapp1', '0070_alter_customcakeorder_pickup_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcakeorder',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customcakeorder',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
