# Generated by Django 5.1.2 on 2025-03-26 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweetdelightsapp1', '0071_alter_customcakeorder_pickup_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customcakeorder',
            name='discount',
        ),
    ]
