# Generated by Django 5.1.2 on 2025-03-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetdelightsapp1', '0074_customcakeorder_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcakeorder',
            name='is_different_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customcakeorder',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
